logging:
  level:
    tk.mybatis: DEBUG
    cn.turing.firecontrol.admin: DEBUG
spring:
  application:
    name: turing-admin
  datasource:                   
    url: jdbc:mysql://host:3306/turing_admin?useUnicode=true&characterEncoding=UTF8
                              
mybatis:
  basepackage: cn.turing.firecontrol.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: 'classpath:mapper/*.xml'

server:
  port: 8762

#配置swagger
swagger:
  enabled: true
  base-package: cn.turing.firecontrol.admin
  title: Admin Back
  version: 1.0.0.SNAPSHOT
  description: Admin Back后端服务
  contact:
    name: 老彭

auth:
  serviceId: turing-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 单位：分钟
  client:
    id: turing-admin
    secret: 123456
    token-header: client-token

#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: redis.tmc-v1
  port: 6379
  password: 123456
  timeout: 2000
  # 服务或应用名                   
  sysName: turing-admin
  enable: true
  database: 0
# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop:
    enabled: true

mapper:
  mappers: cn.turing.firecontrol.common.mapper.CommonMapper
