spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  datasource:
    name: turing
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: host
    password: Turing2018
    port: 6379
    database: 0
  elasticsearch:
    cluster-name: cluster-name
    cluster-nodes: host:9300



  rabbitmq:
    host: host
    port: 5672
    username: rabbitmq
    password: 123456
    template:
      retry: # 重试
        enabled: true
        initial-interval: 2000
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

server:
  tomcat:
    uri-encoding: UTF-8


eureka:
  client:
    healthcheck:
      enabled: true


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000


jwt:
  token-header: Authorization
  expire: 3600 # 单位秒
  rsa-secret: xx1WET12^%3^(WE45
  user-service: turing-admin

management:
  security:
    enabled: false
endpoints:
  enabled: false


# 阿里云推送配置信息
vms:
  aliyun:
    accessKeyId:
    accessKeySecret:
    calledNumber:
    templateNo:
    fireTemplateNo:

# 阿里云推送配置信息
sms:
  feige:
    account:
    pwd:
    signId:
    alarmTemplateId:
    earlyWarningTemplateId:
    fireTemplateId:
  ailiyun:
    SignName:
    fireTemplateNo:
    videoTemplateNo:



tmc:
  config:
    rabbitmq:
      abnormal:
        websocket:
          exchange: tmc.alarm.${spring.profiles.active}
          routingKey: websocket
          queue: ${tmc.config.rabbitmq.abnormal.websocket.exchange}.${spring.cloud.client.ipAddress}
        msg:
          exchange: tmc.abnormal.${spring.profiles.active}
          routingKey: abnormal
          queue: tmc.abnormal.${spring.profiles.active}
    elasicSearch:
      abnormal:
        index: sensor_abnormal
        type:
          firedoor: firedoor

#新加 mybatis中字段驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true          

                
                                      