spring:
    application:
        name: turing-auth
    datasource:
      url: jdbc:mysql://host:3306/turing_auth?useUnicode=true&characterEncoding=UTF8
      druid:
        stat-view-servlet:
          loginUsername: root
          loginPassword: 123456

mybatis:
    basepackage: cn.turing.firecontrol.auth.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

server:
    port: 9777 #启动端口

client:
  id: turing-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

redis:
  turing-key: xx288&^^%$!@#4dc
  turing-iv: 0123456789abcdef

# 配置swagger
swagger:
    enabled: true
    base-package: cn.turing.firecontrol.auth
    title: turing-auth
    version: 1.0.0.SNAPSHOT
    description: 鉴权服务
    contact:
        name: auth

mapper:
  mappers: cn.turing.firecontrol.common.mapper.CommonMapper


logging:
  level:
    root: info
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
    org.springframework.security: info
